sudo: false

notifications:
  email:
    - mdboom@gmail.com

  on_success: change
  on_failure: always

env:
  global:
    - secure: "d74wliUUljSp8krWqiilGA8YFVJm3WW/bdyIfQPbSACXZ0xRU02VDNjd3Kl8uiwAZh88GwS4Im+zVs8nxLZjachb0Ot8mSaPzblwDWkJ3emQtEyWHZ+7+AeiHCBtpuEyV9rs44cGD44zfPn85OeGtsNvcmPnbTycMJ4skCnSfs0="

language: python

branches:
  only:
    - master

before_install:
  - pip install 'sphinx<1.6'
  - pip install sphinx_bootstrap_theme
  - pip install jsonschema
  - bash -x ./install-texlive.sh
  - export PATH=$PWD/texlive/bin/x86_64-linux:$PATH

install:
  - make html latexpdf

script:
  - bash -x ./travis_deploy.sh
