sudo: false

notifications:
  email:
    - mdboom@gmail.com

  on_success: change
  on_failure: always

language: python

branches:
  only:
    - master

before_install:
  - pip install sphinx
  - pip install sphinx_bootstrap_theme
  - pip install git+https://github.com/Julian/jsonschema@97e42bfe2ec8767ffbb76ddb84625c06cbaf0184
  - bash -x ./install-texlive.sh
  - export PATH=$PWD/texlive/bin/x86_64-linux:$PATH

install:
  - make html latexpdf
  - cp build/latex/*.pdf build/html

deploy:
  provider: pages
  skip-cleanup: true
  githup-token: $GITHUB_TOKEN
  local-dir: build/html 
  on:
    branch: master
